
import { Rubik } from 'next/font/google'
import './globals.css'
import Navbar from "../widgets/Header"
import Footer from "../widgets/Footer"
import React from 'react'
import { ReactQueryProvider } from '../reactQuery';




const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Rashid',
  description: 'Generated by create next app',
}

const RootLayout =({ children })=> {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href='/logo.png' />
      </head>
      <body className={rubik.className}>
        <div className='main'>
        <Navbar/>
        <ReactQueryProvider>
        <div className='flex-center block' >{children}</div>
        </ReactQueryProvider>
        <Footer/>
        </div>
        </body>
    </html>
  )
}
export default RootLayout;
