
import { Rubik } from 'next/font/google'
import './globals.css'
import Navbar from "./comps/Navbar"
import Footer from "./comps/Footer"
import React from 'react'
import AnimatedBlock from './ui/gsap';
import AmimateHead from './ui/headerGsap';


const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

 import { ReactQueryProvider } from './ReactQueryProvider';



const RootLayout =({ children })=> {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href='/logo.png' />
      </head>
      <body className={rubik.className}>
       
        <div className='main'>
        <AmimateHead ><Navbar/></AmimateHead>
        <ReactQueryProvider>
          <AnimatedBlock>
        <div className='flex-center block' >{children}</div>
        </AnimatedBlock>
        </ReactQueryProvider>
        <Footer/>
        </div>
        
        </body>
    </html>
  )
}
export default RootLayout;
